services:
  newspaper:
    command: "npm run dev"
    build:
      context: "./newspaper"
    env_file:
      - ./.env
    init: true
    depends_on:
      - "postgres"
    ports:
      - ${NEWSPAPER_PORT}:3000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
    volumes:
      - minio:/data1

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

  bootstrap:
    build:
      context: "./"
      dockerfile: "./bootstrap/Dockerfile"
    env_file:
      - .env
      - ./newspaper/.env
    command: "npm run prisma:migrate"
    tty: true
    depends_on:
      - "postgres"
    volumes:
      - "./bootstrap/inventory:/opt/app/inventory"
      - "./newspaper/prisma:/opt/app/prisma"
      - "./newspaper/.env:/opt/app/.env"

volumes:
  bootstrap:
  minio:
